== Part 1: Fundamentals of Java API Development

=== Introduction to Java

O Java é, sem dúvida, uma das linguagens de programação de computadores mais importantes e amplamente adotadas do mundo. Mas isso não aconteceu do dia para a noite. Sua rica história e evolução ao longo dos anos que se seguiram desde sua primeira versão em 1995 trazem consigo um grande legado de inovação e sucesso que contribuiu de maneira inegável ao cenário da programação de software moderno.

Origiunda de uma ideia inovadora em 1991 focada no desenvolvimento de software que seriam embarcados em vários equipamentos eletrônicos e eletrodomésticos como televisores, micro-ondas, controle remotos, entre outros, guiaram o Java para ser uma linguagem de programação para desenvolver aplicações robustas, portáveis, interoperáveis e seguras. Tais capacidades ganharam ainda mais força com o alvorecer da Wide World Web. A habilidade de baixar e executar  de maneira segura programas Java nos navegadores web (Java Applets) foram imprescindíveis para a adoção da linguagem naquela época. A forma que as applets disponibilizavam uma execução segura e robusta moldaram a forma que conhecemos a internet hoje.

Vale lembrar que a internet evoluiu, e que, por questões de segurança, tecnologias como Flash e plugins Java para navegadores web foram gradualmente caindo em desuso e a criação de novos padrões web foram necessários. Apesar de tais mudança, a maneira como a arquitetura e a liguagem foi contruída continuam sendo bem sucedidas e relevantes para o desenvolvimento de software moderno no backend.








Oriund from an innovative idea in 1991 focused on software development for embedded devices such as set-top boxes, television, and so on.



There is a rich history behind the success of this technology. Key features like portability, robustness, interoperability, and safety made Java the language programming most quickly widely adopted in the software development market in computing history.





=== Introduction to APIs


=== Introduction to Design Principles


=== Introduction to Microservices


